version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Poetry"
      include: "scope"
    ignore:
      # ignore patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
