name: Deploy to Github Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv v0.4.2
        run: curl -LsSf https://astral.sh/uv/0.4.2/install.sh | sh
      
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.x'
      
      - name: Install Dependencies
        run: uv sync
      
      - name: Deploy GH Pages
        run: uv run mkdocs gh-deploy --force
